# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# # pre-commit hooks
# -   repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v3.2.0
#     hooks:
#     -   id: trailing-whitespace # 删除行尾空格
#     -   id: end-of-file-fixer
#     -   id: check-yaml
#     # -   id: check-added-large-files #不允许大文件保存（不推荐） # Uncomment if you want to check for large files
  # 语法检查 (flake8)
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]  # 可选插件
# import sort (isort)
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black]  # 兼容 black 的配置
