[project]
name = "CellFateExplorer"
version = "0.1.0"

[tool.black]
line-length = 150

[tool.flake8]
max-line-length = 150
ignore = [
    "E203",  # 空格问题（black 会处理）
    # "E501",  # 行长度（由 max-line-length 控制）
    "W503",  # 运算符换行风格（black 兼容）
    "B008",  # 函数默认参数的可变对象（如 `def foo(a=[])`）
    "B006",  # 可变默认参数（如 `def foo(a=[])`）
    "E741",  # 模糊的变量名（如 `l`, `O`, `I`）
] # 忽略的错误类型（根据项目需求调整）

# replace "pytest.ini"
[tool.pytest.ini_options]
# addopts = "-v --color=yes" # single test function show
testpaths = ["tests"]
filterwarnings = [
    "ignore",  # 忽略所有警告
]
# 核心配置
addopts = [
    "--capture=sys",  # 严格捕获所有输出
    "-q",             # 静默模式
    "--no-header",    # 隐藏头部信息
    "--no-summary",   # 隐藏统计信息
    "--tb=no",       # 隐藏错误回溯
    "--no-showlocals" # 隐藏局部变量
]
# 日志控制
log_cli = false
log_level = "CRITICAL"  # 只显示严重错误


# TODO: requirement.txt