import json
import os
import pickle
import subprocess
import tempfile
import threading

import yaml
from anndata import AnnData

from .._logging import logger
from ..data import FateAnnData
from ..util import parse_bash_resource_usage_string
from .fate_backend import Backend, Definition


# 读取subprocess子进程输出,
def print_output(print=logger.info, output_list=[]):
    def fun(
        pipe,
        prefix,
    ):
        """print output from a pipe"""
        for line in iter(pipe.readline, ""):
            if line:
                print(f"{prefix}{line.rstrip()}")
                if output_list is not None:
                    output_list.append(line.rstrip())
        pipe.close()

    return fun


class CondaBackend(Backend):
    """Specific implementation of abstract Backend class using Python functions."""

    def __init__(self, function_name="cf_paga", conda_name="cfe"):
        logger.debug("CondaBackend __init__")
        self.function_name = function_name
        self.conda_name = conda_name
        self.load_backend()

    def load_backend(self):
        # conda backend just load definition
        self._load_definition()
        # TODO: test if conda environment is available, if not, raise error

    def preprocess(self, fadata: AnnData, prior_information: dict, parameters: dict, tmp_wd: str) -> None:
        """save adata h5ad, prior information and parameters json file in tmp_wd dir"""
        fadata.write(filename=f"{tmp_wd}/adata.h5ad")

        with open(f"{tmp_wd}/prior_information.json", "w") as f:
            json.dump(prior_information, f)

        with open(f"{tmp_wd}/parameters.json", "w") as f:
            json.dump(parameters, f)

    def execute(self, tmp_wd: str, benchmark_resource: False) -> dict:
        """conda run, save dict.pkl in tmp_wd dir, return trajectory_dict

        Args:
            tmp_wd (str): tmp working dir for docker mount and saving h5ad.h5, json file

        Returns:
            dict: trajectory dict
        """
        trajectory_dict = {}

        parse_args_script = "/home/huang/PyCode/scRNA/CellFateExplorer/CellFateExplorer/cfe/method/function/parse_args.py"

        # construct command
        cmd = f"python {parse_args_script} --function_name={self.function_name} --adata_path={tmp_wd}/adata.h5ad --prior_information={tmp_wd}/prior_information.json --parameters={tmp_wd}/parameters.json --output_filename={tmp_wd}/output.pkl"
        if benchmark_resource:
            cmd = f"/usr/bin/time -v {cmd}"
        cmd = f"conda run -n {self.conda_name} --no-capture-output {cmd}"  # use conda environment to run
        logger.info(f"cmd: {cmd}")

        # execuate command
        process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        # remove unimportant warning log
        stderr_lines = []
        threading.Thread(target=print_output(logger.info), args=(process.stdout, "[stdout]"), daemon=True).start()
        threading.Thread(target=print_output(logger.debug, stderr_lines), args=(process.stderr, "[stderr]"), daemon=True).start()
        # wait for process
        process.wait()

        # read output pkl
        output_pkl_filename = f"{tmp_wd}/output.pkl"
        if not os.path.exists(output_pkl_filename):
            # no h5 file generated by docker, show error log
            logger.error("Conda error, no output.pkl generated by conda command!!!")
        else:
            logger.debug("Conda finish")
            with open(f"{tmp_wd}/output.pkl", "rb") as f:
                trajectory_dict = pickle.load(f)
            if benchmark_resource:
                # read usage string and transfer to dict
                usage_string = "".join(stderr_lines)
                logger.debug(f"resource usage string: {usage_string}")
                usage_dict = parse_bash_resource_usage_string(usage_string)
                logger.debug(f"resource usage dict: {usage_dict}")
                trajectory_dict["resource_usage"] = usage_dict
            return trajectory_dict

    def run(
        self,
        fadata: FateAnnData,
        parameters: dict,
    ):
        """run"""
        # check if benchmark resource from parameters.
        benchmark_resource = False
        if "benchmark_resource" in parameters:
            benchmark_resource = parameters["benchmark_resource"]
            del parameters["benchmark_resource"]

        prior_information = self._extract_prior_information(fadata, self.definition.get_inputs_df())  # check prior information and add to fadata
        parameters = self.definition.get_parameters(parameters)
        adata = fadata.to_anndata(delete_trajectory=True)  # avoid other trajectory IO

        with tempfile.TemporaryDirectory() as tmp_wd:
            logger.debug(f"Temp wd: {tmp_wd}")
            self.preprocess(adata, prior_information, parameters, tmp_wd)

            trajectory_dict = self.execute(tmp_wd, benchmark_resource=benchmark_resource)

            # if multiple wrapper type for a method, it should be shown in trajectory_dict
            # else, read from definition yaml file
            if "wrapper_type" not in trajectory_dict:
                wrapper_type = self.definition["wrapper"]["type"]
                trajectory_dict["wrapper_type"] = wrapper_type[0] if isinstance(wrapper_type, list) else wrapper_type
            fadata.add_trajectory_by_type(trajectory_dict)

            # add resource usage if benchmark_resource is True
            if "resource_usage" in trajectory_dict:
                fadata.add_resource_usage(trajectory_dict["resource_usage"])

    def __call__(self, adata: AnnData, rewrite: bool = True, **parameters):
        """simplified version for self.run"""
        # check if benchmark resource from parameters.
        benchmark_resource = False
        if "benchmark_resource" in parameters:
            benchmark_resource = parameters["benchmark_resource"]
            del parameters["benchmark_resource"]

        with tempfile.TemporaryDirectory() as tmp_wd:
            logger.debug(f"Temp wd: {tmp_wd}")
            self.preprocess(adata, {}, parameters, tmp_wd)
            trajectory_dict = self.execute(tmp_wd, benchmark_resource=benchmark_resource)

            return trajectory_dict

    def __str__(self):
        return f"CondaBackend: function_name-{self.function_name}, load_backend-{self.conda_name}"

    def _load_definition(self) -> None:
        """load definition from yaml file and ceate Definition object"""
        definition_file_path = f"{os.path.dirname(__file__)}/definition/{self.function_name}.yml"
        with open(definition_file_path, "r") as file:
            definition_raw = yaml.safe_load(file)

        definition = Definition(definition_raw)
        definition["run"] = {"backend": "python_function", "function_name": self.function_name}
        self.definition = definition
