import json
import os
import pickle
import subprocess
import tempfile
import threading

import yaml

from .._logging import logger
from ..data import FateAnnData
from .fate_backend import Backend, Definition


# 读取subprocess子进程输出,
def print_output(print=logger.info):
    def fun(
        pipe,
        prefix,
    ):
        """print output from a pipe"""
        for line in iter(pipe.readline, ""):
            if line:
                print(f"{prefix}{line.rstrip()}")
        pipe.close()

    return fun


class CondaBackend(Backend):
    """Specific implementation of abstract Backend class using Python functions."""

    def __init__(self, function_name="cf_paga", conda_name="cfe"):
        logger.debug("CondaBackend __init__")
        self.function_name = function_name
        self.conda_name = conda_name
        self.load_backend()

    def load_backend(self):
        # conda backend just load definition
        self._load_definition()
        # TODO: test if conda environment is available, if not, raise error

    def preprocess(self, fadata: FateAnnData, prior_information: dict, parameters: dict, tmp_wd: str) -> None:
        """save adata h5ad, prior information and parameters json file in tmp_wd dir"""
        fadata.write_h5ad(filename=f"{tmp_wd}/adata.h5ad")

        with open(f"{tmp_wd}/prior_information.json", "w") as f:
            json.dump(prior_information, f)

        with open(f"{tmp_wd}/parameters.json", "w") as f:
            json.dump(parameters, f)

    def execute(self, tmp_wd: str) -> dict:
        """conda run, save dict.pkl in tmp_wd dir, return trajectory_dict

        Args:
            tmp_wd (str): tmp working dir for docker mount and saving h5ad.h5, json file

        Returns:
            dict: trajectory dict
        """
        trajectory_dict = {}

        parse_args_script = "/home/huang/PyCode/scRNA/CellFateExplorer/CellFateExplorer/cfe/method/function/parse_args.py"

        # construct command
        cmd = f"""
            conda run -n {self.conda_name} --no-capture-output \
                python {parse_args_script}\
                    --function_name={self.function_name}\
                    --adata_path={tmp_wd}/adata.h5ad\
                    --prior_information={tmp_wd}/prior_information.json\
                    --parameters={tmp_wd}/parameters.json\
                    --output_filename={tmp_wd}/output.pkl
            """
        # execuate command
        process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        # remove unimportant warning log
        threading.Thread(target=print_output(logger.info), args=(process.stdout, "[stdout]"), daemon=True).start()
        threading.Thread(target=print_output(logger.debug), args=(process.stderr, "[stderr]"), daemon=True).start()
        # wait for process
        process.wait()

        # read output pkl
        output_pkl_filename = f"{tmp_wd}/output.pkl"
        if not os.path.exists(output_pkl_filename):
            # no h5 file generated by docker, show error log
            logger.error("Conda Error, no output.pkl generated by conda command!!!")
        else:
            logger.debug("Docker Finish")
            with open(f"{tmp_wd}/output.pkl", "rb") as f:
                trajectory_dict = pickle.load(f)
            return trajectory_dict

    def run(
        self,
        fadata: FateAnnData,
        parameters: dict,
    ):
        """run"""
        # TODO: parameters update function should move to Definition
        prior_information = self._extract_prior_information(fadata, self.definition.get_inputs_df())  # check prior information and add to fadata
        parameters = self.definition.get_parameters(parameters)

        with tempfile.TemporaryDirectory() as tmp_wd:
            logger.debug(f"Temp wd: {tmp_wd}")
            self.preprocess(fadata, prior_information, parameters, tmp_wd)

            trajectory_dict = self.execute(tmp_wd)

            # if multiple wrapper type for a method, it should be shown in trajectory_dict
            # else, read from definition yaml file
            if "wrapper_type" not in trajectory_dict:
                wrapper_type = self.definition["wrapper"]["type"]
                trajectory_dict["wrapper_type"] = wrapper_type[0] if isinstance(wrapper_type, list) else wrapper_type
            fadata.add_trajectory_by_type(trajectory_dict)

    def _load_definition(self) -> None:
        """load definition from yaml file and ceate Definition object"""
        definition_file_path = f"{os.path.dirname(__file__)}/definition/{self.function_name}.yml"
        with open(definition_file_path, "r") as file:
            definition_raw = yaml.safe_load(file)

        definition = Definition(definition_raw)
        definition["run"] = {"backend": "python_function", "function_name": self.function_name}
        self.definition = definition
