import json
import os
import pickle
import tempfile
import threading
import time

import docker
from anndata import AnnData

from .._logging import logger
from ..data import FateAnnData
from ..util import parse_docker_resource_usage_string_list
from .fate_backend import DockerBackend


class CFEDockerBackend(DockerBackend):
    """CFEDockerBackend: specific implementation of abstract Backend class using CFE Docker."""

    def __init__(self, function_name="comp1", image_id: str = "huangzhaoyang/comp1:0.0.1"):
        """Initialize the CFEDockerBackend class.
        Args:
            image_id (_type_, optional): image id.
        """
        self.function_name = function_name
        logger.debug("CFEDockerBackend __init__")

        self.function_name = function_name
        self.image_id = image_id
        self.load_backend()  # implemented in DockerBackend

    def load_backend(self):
        self._load_image()
        self._load_function(self.function_name)

    def __call__(self, adata: AnnData, rewrite: bool = True, **parameters):
        """simplified version for self.run"""
        with tempfile.TemporaryDirectory() as tmp_wd:
            logger.debug(f"Temp wd: {tmp_wd}")
            self.preprocess(adata, {}, parameters, tmp_wd)
            trajectory_dict = self.execute(tmp_wd)
            return trajectory_dict

    def preprocess(self, adata: AnnData, parameters: dict, tmp_wd: str) -> None:
        """save adata h5ad , prior information and parameters json file in tmp_wd dir

        Args:
            adata (AnnData): _description_
            parameters (dict): prior information dict
            tmp_wd (str): tmp working dir for docker mount and saving h5ad.h5, json file
        """
        adata_filename = f"{tmp_wd}/adata.h5ad"
        adata.uns["filename"] = "/data/adata.h5ad"  # save filename in uns for function use in docker
        adata.write(filename=adata_filename)

        with open(f"{tmp_wd}/parameters.json", "w") as f:
            json.dump(parameters, f)

    def execute(self, tmp_wd: str, benchmark_resource: bool) -> dict:
        """CFE Docker run, save dict.pkl in tmp_wd dir, return trajectory_dict

        Args:
            tmp_wd (str): tmp working dir for docker mount and saving h5ad.h5, json file

        Returns:
            dict: trajectory dict
        """
        trajectory_dict = {}

        client = docker.from_env()
        start_time = time.time()
        container = client.containers.run(
            image=self.image_id,
            command=f"python run.py --function_name {self.function_name}",  # input and output path are fixed
            volumes=[f"{tmp_wd}:/data"],
            working_dir="/code",
            detach=True,
        )  # all are saved in "/data" dir and sync to master

        # real time stat and log list
        stats_list = []

        def collect_stats():
            for stat in container.stats(stream=True, decode=True):
                stats_list.append(stat)

        stats_thread = threading.Thread(target=collect_stats, daemon=True)
        stats_thread.start()

        def collect_logs():
            for line in container.logs(stream=True, follow=True, stdout=True, stderr=True):
                logger.debug(line.decode("utf-8").strip())

        log_thread = threading.Thread(target=collect_logs, daemon=True)
        log_thread.start()

        container.wait()  # wait until docker finish
        end_time = time.time()
        container.stop()
        container.remove()

        output_pkl_filename = f"{tmp_wd}/output.pkl"
        if not os.path.exists(output_pkl_filename):
            # no h5 file generated by docker, show error log
            logger.error("Docker Error!!!")
        else:
            logger.debug("Docker Finish")
            with open(f"{tmp_wd}/output.pkl", "rb") as f:
                trajectory_dict = pickle.load(f)
            if benchmark_resource:
                usage_dict = parse_docker_resource_usage_string_list(stats_list)
                usage_dict["time"] = end_time - start_time  # mannuly add time
                logger.debug(f"resource usage dict: {usage_dict}")
                trajectory_dict["resource_usage"] = usage_dict
            return trajectory_dict

    # def postprocess(self, fadata: FateAnnData, trajectory_dict: dict) -> None:
    #     """Save trajectory_dict

    #     Args:
    #         fadata (FateAnnData): FateAnnData to be added the trajectory dict
    #         trajectory_dict (dict): trajectory dict
    #     """
    #     fadata.add_trajectory_by_type(trajectory_dict)

    def run(self, fadata: FateAnnData, parameters: dict) -> None:
        """Run cfe docker pipeline to infer the trajectory

        Args:
            fadata (FateAnnData): ateAnnData to be added the trajector
            parameters (dict): parameter dict
        """
        # check if benchmark resource from parameters.
        benchmark_resource = self._check_benchmark_resource(parameters)

        # prepare data and parameters
        adata = fadata.to_anndata(delete_trajectory=True)
        self._get_parameters(fadata, parameters)

        # execute method, save input and output file in tmp dir
        with tempfile.TemporaryDirectory() as tmp_wd:
            logger.debug(f"Temp wd: {tmp_wd}")
            self.preprocess(adata, parameters, tmp_wd)

            trajectory_dict = self.execute(tmp_wd, benchmark_resource)

            fadata.add_trajectory_by_type(trajectory_dict)

            # add resource usage if benchmark_resource is True
            if "resource_usage" in trajectory_dict:
                fadata.add_resource_usage(trajectory_dict["resource_usage"])

    def __str__(self):
        return f"CFE Docker Backend: {self.function_name} in docker image '{self.image_id}'"
