import json
import os
import subprocess
import tempfile
import threading
import time

import docker
import h5py
import numpy as np
import pandas as pd

# import rpy2.robjects as ro
import yaml
from scipy import sparse as sp

# from .._logging import logger, print_output
from .._logging import logger
from .._settings import settings
from ..data import FateAnnData

# from ..util import (
#     parse_bash_resource_usage_string,
#     parse_docker_resource_usage_string_list,
# )
from ..util import parse_docker_resource_usage_string_list
from .fate_backend import DockerBackend


class DynverseDockerBackend(DockerBackend):
    """DockerBackend: specific implementation of abstract Backend class using Dynverse Docker."""

    def __init__(self, image_id: str = "dynverse/ti_comp1:v0.9.9.01"):
        """Initialize the DynverseDockerBackend class.

        Args:
            image_id (str, optional): image id.
        """
        # logger.debug("DockerBackend __init__")

        self.image_id = image_id
        self.load_backend()  # implemented in DockerBackend, get self.entrypoint

    def load_backend(self):
        self._load_image()  # load image
        self._load_definition()  # load definition yaml file

    def preprocess(self, inputs: dict, parameters: dict, priors: dict, tmp_wd: dict, seed: int = 0) -> None:
        """Preproces: create input.h5 for dynverse docker execute

        ref: pydynverse/wrap/method_create_ti_method_container._method_execution_preproc_container

        Args:
            inputs (dict): input dict
            parameters (dict): parameter dict
            priors (dict): prior information dict
            tmp_wd (dict): tmp working dir for docker mount and saving input.h5
            seed (int, optional): random seed.
        """

        task = inputs
        task["parameters"] = parameters
        task["priors"] = priors
        task["seed"] = seed
        task["verbose"] = True
        write_h5(task, f"{tmp_wd}/input.h5")  # json->h5

    # def execute_deprecated_deprecated(self, tmp_wd: str, benchmark_resource: bool) -> "DynverseDockerOutput":
    #     """Execute: Dynverse docker execute with bash command and parse result file "output.h5"
    #     try to use /usr/bin/time in docker container, but it is not available
    #     """

    #     image_id = self.definition["run"]["image_id"]
    #     args = "--dataset /ti/input.h5 --output /ti/output.h5"
    #     cmd = f"docker run --rm -v {tmp_wd}:/ti -w /ti/workspace {image_id} {args}"
    #     if benchmark_resource:
    #         # 0. command "/usr/bin/time" should move into docker command,
    #         # cmd = f"/usr/bin/time -v docker run --rm -v {tmp_wd}:/ti -w /ti/workspace {image_id} {args}"
    #         # the resource result is for docker client(such as pull, start container...), not for container running.

    #         # 1. change entrypoint program with "/usr/bin/time"
    #         entrypoint = self.entrypoint[0]

    #         # # (1) solution1: add it in docker command
    #         # if entrypoint.split('.')[-1] == 'R':
    #         #     entrypoint = f"Rscript {entrypoint}"
    #         # else:
    #         #     entrypoint = f"python {entrypoint}"
    #         # cmd = f" {cmd} /usr/bin/time -v {entrypoint} --dataset /ti/input.h5 --output /ti/output.h5"

    #         # (2) solution 2: create new entrypoint file, specify it in bash command. However, "/usr/bin/time" dose not exist in container
    #         new_entrypoint = f"{tmp_wd}/entrypoint.sh"
    #         with open(new_entrypoint, "w") as f:
    #             f.write("#!/bin/bash\n")
    #             # f.write(f"/usr/bin/time -v {entrypoint} {args}") # NOTE: fail to time
    #             f.write(f"time {entrypoint} {args}")
    #         os.chmod(new_entrypoint, 0o755)
    #         cmd = f"docker run --rm -v {tmp_wd}:/ti -w /ti/workspace --entrypoint /ti/entrypoint.sh {image_id} {args}"

    #     logger.info(f"running docker command: {cmd}")

    #     # execuate command
    #     process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    #     # remove unimportant warning log
    #     stderr_lines = []
    #     threading.Thread(target=print_output(logger.info), args=(process.stdout, "[stdout]"), daemon=True).start()
    #     threading.Thread(target=print_output(logger.debug, stderr_lines), args=(process.stderr, "[stderr]"), daemon=True).start()
    #     # wait for process
    #     process.wait()

    #     # read output h5
    #     output_h5_filename = f"{tmp_wd}/output.h5"
    #     if not os.path.exists(output_h5_filename):
    #         # no h5 file generated by docker, show error log
    #         logger.error("Docker error, no output.h5 generated by docker command!!!")
    #     else:
    #         logger.debug("Docker Finish")
    #         dynverse_docker_output = read_h5(f"{tmp_wd}/output.h5")  # read docker result h5
    #         if benchmark_resource:
    #             # read usage string and transfer to dict
    #             usage_string = "".join(stderr_lines)
    #             logger.debug(f"resource usage string: {usage_string}")
    #             usage_dict = parse_bash_resource_usage_string(usage_string)
    #             logger.debug(f"resource usage dict: {usage_dict}")
    #             dynverse_docker_output["resource_usage"] = usage_dict
    #         return dynverse_docker_output

    def execute(self, tmp_wd: str, benchmark_resource: bool) -> "DynverseDockerOutput":
        """Execute: Dynverse docker execute and parse result file "output.h5"

        ref: pydynverse/wrap/method_create_ti_method_container._method_execution_execute_container

        Args:
            tmp_wd (str): tmp working dir for docker mount and saving input.h5

        Returns:
            DynverseDockerOutput:  parse result file "output.h5"
        """
        args = ["--dataset", "/ti/input.h5", "--output", "/ti/output.h5"]
        # TODO: show dynverse docker debug information
        # args = ["--dataset", "/ti/input.h5", "--output", "/ti/output.h5", "--verbosity", "3"]
        client = docker.from_env()
        start_time = time.time()
        container = client.containers.run(
            image=self.definition["run"]["image_id"],
            command=args,  # r R script command args in Docker
            volumes=[f"{tmp_wd}:/ti"],
            working_dir="/ti/workspace",
            detach=True,
        )

        # real time stat and log list
        stats_list = []

        def collect_stats():
            for stat in container.stats(stream=True, decode=True):
                stats_list.append(stat)

        stats_thread = threading.Thread(target=collect_stats, daemon=True)
        stats_thread.start()

        def collect_logs():
            for line in container.logs(stream=True, follow=True, stdout=True, stderr=True):
                logger.debug(f"[dynverse docker]{line.decode('utf-8').strip()}")

        log_thread = threading.Thread(target=collect_logs, daemon=True)
        log_thread.start()

        container.wait()  # wait until docker finish
        end_time = time.time()
        container.stop()
        container.remove()

        output_h5_filename = f"{tmp_wd}/output.h5"
        if not os.path.exists(output_h5_filename):
            # no h5 file generated by docker, show error log
            logger.error("Docker Error!!!")
        else:
            logger.debug("Docker Finish")
            dynverse_docker_output = read_h5(f"{tmp_wd}/output.h5")  # read docker result h5
            if benchmark_resource:
                usage_dict = parse_docker_resource_usage_string_list(stats_list)
                usage_dict["time"] = end_time - start_time  # mannuly add time
                logger.debug(f"resource usage dict: {usage_dict}")
                dynverse_docker_output["resource_usage"] = usage_dict
            return dynverse_docker_output

    def postprocess(self, fadata: FateAnnData, trajectory: dict) -> None:
        """Postprocess: call fadata.add_trajectory

        Args:
            fadata (FateAnnData): FateAnnData to be added the trajectory dict
            trajectory (dict): trajectory dict
        """
        # trajectory is a "DynverseDockerOutput" object that have been transformed from other wrapper
        fadata.raw_wrapper_dict = {}  # dynverse docker can't get raw wrapper dict
        fadata.add_trajectory(
            milestone_network=trajectory.milestone_network,
            divergence_regions=trajectory.divergence_regions,
            milestone_percentages=trajectory.milestone_percentages,
        )

    def run(self, fadata: FateAnnData, parameters: dict):
        """Run dynverse docker pipeline to infer the trajectory

        Args:
            fadata (FateAnnData): FateAnnData to be added the trajectory
            parameters (dict): parameter dict
        """
        # check if benchmark resource from parameters.
        benchmark_resource = self._check_benchmark_resource(parameters)

        # only parse definition file for dynverse docker
        input_df = self.definition.get_inputs_df()
        logger.debug(f"definition input_df: {input_df}")
        inputs = self._extract_inputs(fadata, input_df)  # extract main input, expression matrix
        priors = self._extract_prior_information(fadata, input_df)  # extract prior information
        parameters = self.definition.get_parameters(parameters)

        with tempfile.TemporaryDirectory() as tmp_wd:
            # /tmp/*** temp dir for docker
            logger.debug(f"Temp wd: {tmp_wd}")

            # preprocess
            self.preprocess(inputs, parameters, priors, tmp_wd)

            # method run
            trajectory = self.execute(tmp_wd, benchmark_resource)

            # postprocess
            self.postprocess(fadata, trajectory)

            if "resource_usage" in trajectory:
                fadata.add_resource_usage(trajectory["resource_usage"])

    def _extract_inputs(self, fadata: FateAnnData, inputs_df: pd.DataFrame) -> dict:
        """extract input dict fom definition

        ref: PyDynverse/pydynverse/wrap/method_extract_args.py _method_extract_inputs

        Args:
            fdata (FateAnnData): FateAnnData object
            inputs_df (pd.DataFrame): inputs_df from definition.yml

        Returns:
            dict: input dict
        """

        # logger.debug("FateMethod _extract_inputs")

        # extract model input expression matrix
        input_ids = inputs_df["input_id"][inputs_df["type"] == "expression"].tolist()
        inputs = {}
        if "counts" in input_ids:
            inputs["counts"] = fadata.layers["counts"]
        if "expression" in input_ids:
            inputs["expression"] = fadata.X
        # main expression matrix, for example, Component1 and Slingshot need "expression", while monocle_ddrtree need "counts"
        inputs["expression_id"] = input_ids[0]
        # add cell and gene ids
        inputs["cell_ids"] = fadata.obs.index.tolist()
        inputs["feature_ids"] = fadata.var.index.tolist()
        return inputs

    def _load_definition(self):
        """
        extract and parse definition.yml, including description, required parameters and prior knowledge

        ref: pydynverse.wrap.container_get._container_get_definition
        """
        with tempfile.TemporaryDirectory() as tmp_wd:
            # start docker container
            client = docker.from_env()
            container = client.containers.run(
                entrypoint="cp /code/definition.yml /copy_mount/definition.yml",  # aim copy dir
                image=self.image_id,
                volumes=[f"{tmp_wd}:/copy_mount"],
                detach=True,
            )
            container.wait()
            container.stop()
            container.remove()
            # read and parse yml file
            with open(f"{tmp_wd}/definition.yml", "r") as file:
                definition_raw = yaml.safe_load(file)

        definition = Definition(definition_raw)
        definition["run"] = {"backend": "container", "image_id": self.image_id}
        self.definition = definition

        # Note: Only used for dynverse docker backend

    def _extract_prior_information(self, fadata, inputs_df):
        """
        ref: PyDynverse/pydynverse/wrap/method_extract_args.py _method_extract_priors
        """
        # logger.debug("FateMethod _extract_prior_information")

        # extract prior information from
        cfe_priors = fadata.prior_information
        priors = {}
        # same prior infomation means different key for dynverse_docker and other environment.
        # transfer prior information from cfe style to dynverse style
        cfe2dynverse = {
            "basis": "dimred",
            "start_cell": "start_id",
            # TODO: show available prior infomation
        }
        for k, v in cfe2dynverse.items():
            if k in cfe_priors:
                priors[v] = cfe_priors[k]
        if "cluster" in cfe_priors:
            groups_id = fadata.obs[cfe_priors["cluster"]].tolist()
            priors["groups_id"] = groups_id
            # logger.debug(f"extract .obs['{cfe_priors['cluster']}']({len(groups_id)}) in as prior information `groups_id` key for dynverse ")

        priors_key_set = set(priors.keys())

        # check required priors
        required_prior_ids = inputs_df["input_id"][inputs_df["required"] & (inputs_df["type"] == "prior_information")].tolist()
        required_prior_ids_set = set(required_prior_ids)
        if not (required_prior_ids_set <= priors_key_set):
            # all required priors are necessary, if not, raise error
            missing_priors = required_prior_ids_set - priors_key_set
            msg = f"""
                ! Prior information {','.join(missing_priors)} is missing from dataset {fadata.id} but is required by the method. \n
                -> If known, you can add this prior information using fadata.add_prior_information({' ,'.join([str(i)+' = <prior>' for i in missing_priors])}). \n
                -> Otherwise, this method cannot be used.
            """
            raise Exception(msg)
        required_prior = {k: priors[k] for k in required_prior_ids}
        logger.debug(f"extract required priors: {required_prior.keys()}")

        # check optional priors
        optional_prior_ids = inputs_df["input_id"][(~inputs_df["required"]) & (inputs_df["type"] == "prior_information")].tolist()
        optional_prior_ids_set = set(optional_prior_ids)
        if not (optional_prior_ids_set <= priors_key_set):
            # all optional priors are not necessary, enven if not all are provided, only warning
            missing_priors = list(optional_prior_ids_set - priors_key_set)
            msg = f"""
                Prior information {','.join(missing_priors)} is optional, but missing from dataset {fadata.id}. \n
                Will not give this prior to method.
            """
            logger.warning(msg)
        optional_prior = {k: priors[k] for k in list(optional_prior_ids_set & priors_key_set)}  # remove irrelevant keys
        logger.debug(f"extract optional prior: {optional_prior.keys()}")

        priors = required_prior | optional_prior

        return priors

    def __str__(self):
        return f"Dynverse Docker Backend: docker image '{self.image_id}'"


# ====================================================================================================
# YAML ubject for 'definition.yaml' file


class Definition:
    def __init__(self, definition_raw: dict):
        self.method = definition_raw["method"]
        self.wrapper = definition_raw["wrapper"]
        self.container = definition_raw["container"]
        self.package = definition_raw["package"] if "package" in definition_raw else None
        self.manuscript = definition_raw["manuscript"] if "manuscript" in definition_raw else None
        self.parameters = pd.DataFrame(definition_raw["parameters"]).set_index("id")
        self.run = {}

        # inputs
        inputs = self.wrapper["input_required"]
        inputs = inputs.copy() if isinstance(inputs, list) else [inputs]
        if "input_optional" in self.wrapper:
            input_optional = self.wrapper["input_optional"]
            inputs += input_optional if isinstance(input_optional, list) else [input_optional]

        # extra input, including data and parameters
        params = self.parameters.index.tolist()
        input_id_list = inputs + params
        required_list = [i in self.wrapper["input_required"] for i in input_id_list]
        type_list = []
        for input_id in input_id_list:
            # type column
            if input_id in ["counts", "expression", "expression_future"]:
                type_list.append("expression")
            elif input_id in params:
                type_list.append("parameter")
            else:
                type_list.append("prior_information")
        inputs_df = pd.DataFrame({"input_id": input_id_list, "required": required_list, "type": type_list})
        self.wrapper["inputs"] = inputs_df

    def get_inputs_df(self):
        return self.wrapper["inputs"]

    def get_parameters(self, new_parameters=None):
        default_parameters = self.parameters["default"].to_dict()
        if new_parameters is None:
            # return default parameters
            return default_parameters
        else:
            # merge new parameters and default parameters to get parameters
            parameters = default_parameters
            # parameters.update(new_parameters)
            #
            for k, v in new_parameters.items():
                if k in parameters:
                    if isinstance(v, dict) and self.parameters.loc[k, "update"]:
                        #  for dict parameters, it should be updated by merge but not to replace.
                        parameters[k].update(v)
                    else:
                        parameters[k] = v
                else:
                    logger.warning(f"{k} is not a valid parameter")
            return parameters

    def add_function_wrapper(self, return_function):
        if not return_function:
            # 直接返回字典格式
            return self
        # else:
        #     # 返回函数格式，等待默认参数进一步设置
        #     defaults = get_default_parameters(definition)  # 获取代码函数中的参数默认值

        #     def param_overrider_fun(**kwargs):
        #         # 参数覆盖, 接受代码函数中的参数默认值传入参数并覆盖definition.yml
        #         new_defaults = kwargs
        #         param_names = list(definition["parameters"].index)
        #         for param_name, v in new_defaults.items():
        #             if param_name in param_names:
        #                 definition["parameters"].loc[param_name, "default"] = v
        #             else:
        #                 # 该参数不definition.yml文件里定义
        #                 logger.error(f"Unknown parameter: {param_name}")
        #         return definition

        #     param_overrider_fun.__kwdefaults__ = defaults

        #     return param_overrider_fun

    def __contains__(self, item):
        "check if have attribute"
        return hasattr(self, item)

    def keys(self):
        """return all attibute name, then the function dict() can be used"""
        return self.__dict__.keys()

    def __getitem__(self, key):
        "get attribute"
        return getattr(self, key)

    def __setitem__(self, key, value):
        "set attribute"
        setattr(self, key, value)


# ====================================================================================================
# Dynverse Docker I/O Object
class DynverseDockerInput:
    def __init__(self, expression, expression_id: str, cell_ids: list, feature_ids: list, parameters: dict, priors: dict, seed: int, verbose: bool):
        if sp.isspmatrix_csr(expression):
            expression = expression.tocsc()
            logger.debug("expression transfer to csc from csr")
        self.expression = expression
        self.expression_id = expression_id
        self.cell_ids = cell_ids
        self.feature_ids = feature_ids
        self.parameters = parameters
        self.priors = priors
        self.seed = seed
        self.verbose = verbose

    def save_json(self, input_json_filename):
        self.input_json_filename = input_json_filename
        # mannually extract index for sparse matrix
        expression_dict = {
            "x": self.expression.data.tolist(),
            "i": self.expression.indices.tolist(),
            "p": self.expression.indptr.tolist(),
            "Dim": self.expression.shape,
            "rownames": list(self.cell_ids),
            "colnames": list(self.feature_ids),
        }
        input_json = {
            self.expression_id: expression_dict,
            "expression_id": self.expression_id,
            "parameters": self.parameters,
            "priors": self.priors,
            "seed": self.seed,
            "verbose": self.verbose,
        }
        with open(input_json_filename, "w") as f:
            json.dump(input_json, f)
        logger.debug(f"Save json successfully, path: {input_json_filename}")

    def json2h5(self, input_h5_filename):
        self.input_h5_filename = input_h5_filename
        # call R script to get h5 for dynverse docker running via json.
        Rscript_filename = f"{os.path.dirname(__file__)}/../rscript/docker_input_json2h5.R"
        logger.debug(f"h52json script: {Rscript_filename}")
        command_list = [
            Rscript_filename,
            "--input_json_filename",
            self.input_json_filename,
            "--input_h5_filename",
            input_h5_filename,
        ]
        result = subprocess.run(command_list, capture_output=True, text=True)
        logger.debug(result)
        if result.returncode == 0:
            logger.debug("json2h5 successful!")
        else:
            logger.debug("json2h5 failed!")

    def write_h5_directly(self, input_h5_filename):
        def _write_r_like_h5(attr, attr_obj, h5group):
            group = h5group.create_group(attr)

            if isinstance(attr_obj, sp.csc_matrix):
                # sparse_matrix(R) : csc_matrix(Python)
                # expression
                group.attrs["object_class"] = np.string_("sparse_matrix")
                group.create_dataset("x", data=attr_obj.data.astype(np.float64))
                group.create_dataset("i", data=attr_obj.indices.astype(np.int32))
                group.create_dataset("p", data=attr_obj.indptr.astype(np.int32))
                group.create_dataset("dims", data=np.array(attr_obj.shape, dtype=np.int32))
                group.create_dataset("rownames", data=np.array(self.cell_ids, dtype="S"))
                group.create_dataset("colnames", data=np.array(self.feature_ids, dtype="S"))
            elif isinstance(attr_obj, dict):
                # list(R) : dict(Python)
                group.attrs["object_class"] = "list"
                group.create_dataset("names", data=np.array(list(attr_obj.keys()), dtype="S"))
                sub_data_group = group.create_group("data")
                for k, v in attr_obj.items():
                    _write_r_like_h5(k, v, sub_data_group)  # recursively call
            else:
                # vector(R) : other(Python)
                group.attrs["object_class"] = "vector"
                if isinstance(attr_obj, bool):
                    group.create_dataset("data", data=np.array([attr_obj], dtype=np.bool_))
                elif isinstance(attr_obj, int):
                    group.create_dataset("data", data=np.array([attr_obj], dtype=np.int32))
                elif isinstance(attr_obj, float):
                    group.create_dataset("data", data=np.array([attr_obj], dtype=np.float64))
                elif isinstance(attr_obj, str):
                    group.create_dataset("data", data=np.array([attr_obj], dtype="S"))
                elif isinstance(attr_obj, (list, tuple, np.ndarray)):
                    arr = np.array(attr_obj)
                    if arr.dtype.kind in ("U", "O"):
                        # automatically convert to string
                        arr = arr.astype("S")
                    group.create_dataset("data", data=arr)
                else:
                    # default to string
                    group.create_dataset("data", data=np.array([attr_obj], dtype="S"))

        attr_list = ["expression_id", self.expression_id, "parameters", "priors", "seed", "verbose"]
        with h5py.File(input_h5_filename, "w") as f:
            f.attrs["object_class"] = "list"  # list(R):dict(Python)
            f.create_dataset("names", data=np.array(attr_list, dtype="S"))

            # data group
            data_group = f.create_group("data")
            for attr in attr_list:
                if attr == self.expression_id:
                    # for expression matrix, the key is specified by expression_id
                    attr_obj = self.expression
                else:
                    attr_obj = getattr(self, attr)
                _write_r_like_h5(attr, attr_obj, data_group)
        logger.debug(f"Write h5 directly successfully, path: {input_h5_filename}")

    def __str__(self) -> str:
        return f"{self.expression}"  # sparse matrix is most clear


class DynverseDockerOutput:
    def __init__(self):
        self.id = None
        self.pseudotime = None

    def h52json(self, output_h5_filename, output_json_filename):
        self.output_h5_filename = output_h5_filename
        self.output_json_filename = output_json_filename
        # call R script to get dynverse docker result via json.
        Rscript_filename = f"{os.path.dirname(__file__)}/../rscript/docker_output_h52json.R"
        logger.debug(f"h52json script: {Rscript_filename}")
        command_list = [
            Rscript_filename,
            "--output_h5_filename",
            output_h5_filename,
            "--output_json_filename",
            output_json_filename,
        ]
        result = subprocess.run(command_list, capture_output=True, text=True)
        logger.debug(result)
        if result.returncode == 0:
            logger.debug("h52json successful!")
        else:
            logger.debug("h52json failed!")

    def load_json(self):
        with open(self.output_json_filename, "r") as f:
            output_json = json.load(f)
        logger.debug(f"Save json successfully, path: {self.output_json_filename}")
        # extract significant attribute
        self.id = output_json["id"]
        self.cell_ids = output_json["cell_ids"]
        for k, v in output_json.items():
            self.__setattr__(k, v)
        # trajectory result.
        self.milestone_network = pd.DataFrame(self.milestone_network)
        self.milestone_percentages = pd.DataFrame(self.milestone_percentages)
        self.progressions = pd.DataFrame(self.progressions)
        self.divergence_regions = None if (len(self.divergence_regions) == 0) else pd.DataFrame(self.divergence_regions)
        self.dimred = pd.DataFrame(self.dimred, index=self.cell_ids)
        self.dimred_segment_progressions = pd.DataFrame(output_json["dimred_segment_progressions"])
        self.dimred_segment_points = pd.DataFrame(output_json["dimred_segment_points"])

        # save raw json for various output.
        self.output_json = output_json

    def load_h5_directly(self, output_h5_filename):
        def _decode_bytes(x):
            # decode bytes to str, or recursively decode list/ndarray
            if isinstance(x, bytes):
                return x.decode("utf-8")
            if isinstance(x, np.ndarray):
                return [_decode_bytes(i) for i in x]
            return x

        def _read_group(g):
            # read h5 group object recursively
            result = {}
            for k in g.keys():
                obj = g[k]
                if isinstance(obj, h5py.Dataset):
                    value = obj[:]
                    result[k] = _decode_bytes(value)
                elif isinstance(obj, h5py.Group):
                    result[k] = _read_group(obj)
            return result

        df_list = ["milestone_network", "milestone_percentages", "progressions", "divergence_regions"]
        with h5py.File(output_h5_filename, "r") as f:
            data_group = f["data"]
            for key in data_group.keys():
                value = _read_group(data_group[key])
                if key in df_list:
                    # extract data and convert to DataFrame
                    value = pd.DataFrame(value["data"])
                setattr(self, key, value)

        logger.debug(f"load h5 directly successfully, path: {output_h5_filename}")

    def __str__(self) -> str:
        return f"id: {self.id}, trajectory_type: {self.trajectory_type}, attribute_list: {self.__dict__.keys()}"

    def __getitem__(self, key):
        if hasattr(self, key):
            return getattr(self, key)
        else:
            return None
            # raise KeyError(
            #     f"'{self.__class__.__name__}' object has no attribute '{key}'")

    def get(self, key, default=None):
        return self[key]

    def __setitem__(self, key, value):
        setattr(self, key, value)

    def __contains__(self, item):
        return hasattr(self, item)


def write_h5(x, h5_filename, via_json=None):
    if via_json is None:
        via_json = settings["dynverse_docker_via_json"]
    expression_id = x["expression_id"]
    dynverse_docker_input = DynverseDockerInput(
        expression=x[expression_id],  # extract from anndata
        expression_id=expression_id,
        cell_ids=x["cell_ids"],
        feature_ids=x["feature_ids"],
        parameters=x["parameters"],
        priors=x["priors"],
        seed=x["seed"],
        verbose=x["verbose"],
    )
    if via_json:
        input_json_filename = f"{h5_filename[:-3]}.json"  # middle json file
        input_h5_filename = h5_filename
        dynverse_docker_input.save_json(input_json_filename)
        dynverse_docker_input.json2h5(input_h5_filename)
    else:
        dynverse_docker_input.write_h5_directly(h5_filename)


def read_h5(h5_filename, via_json=None):
    if via_json is None:
        via_json = settings["dynverse_docker_via_json"]
    if via_json:
        output_h5_filename = h5_filename
        output_json_filename = f"{h5_filename[:-3]}.json"  # middle json file
        dynverse_docker_output = DynverseDockerOutput()
        dynverse_docker_output.h52json(output_h5_filename, output_json_filename)
        dynverse_docker_output.load_json()
    else:
        dynverse_docker_output = DynverseDockerOutput()
        dynverse_docker_output.load_h5_directly(h5_filename)
    return dynverse_docker_output
