name: Build Method Docker Image

on:
  push:
    branches: [ "dev_method" ]


jobs:
  check-docker-version:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-method-name-list.method_name_list }}
    steps:
      - uses: actions/checkout@v4
      - name: check-docker-version
        id: get-method-name-list
        run: |
          method_name_list='["cf_paga", "cf_comp1"]' # TODO: need check from yaml file
          echo "method_name_list=$method_name_list" >> $GITHUB_OUTPUT

  push-docker-image:
    needs: check-docker-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        var: ${{needs.check-docker-version.outputs.method_name_list}}
        # var: ["cf_paga", "cf_comp1"]
    steps:
      - uses: actions/checkout@v4
      - name: Build, Test, Push
        id: build-test-push
        run: |
          
          bash ./build_method_docker_image.sh ${{ matrix.var }}

