# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    # - name: Set up R 4.4.2
    #   uses: r-lib/actions/setup-r@v2
    #   with:
    #     r-version: "4.4.2"

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.15"

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda install python=3.10.15

    # - name: Check Docker R Python version
    #   run: |
    #     docker --version
    #     R --version
    #     python --version
    #     docker pull  huangzhaoyang/cf_paga:0.0.1

    - name: Install Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz graphviz-dev
        pip install pygraphviz

    - name: Install dependencies
      run: |
        ls
        # conda env update --file environment.yaml --name base
        # pip install cafe-release # install from PyPI
        pip install -e . # install from pyproject.toml file

    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 300 chars wide
        flake8 --count --exit-zero --max-complexity=10 --max-line-length=300 --ignore E714 --statistics  cafe/* tests/*

    - name: Add project root to PYTHONPATH
      run: |
       PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"

    - name: Test with pytest
      run: |
        pip install rpy2==3.3.0
        mkdir -p ./tests/plot/img ./cafe
        conda install pytest
        pytest -m "not local"
